### ISSUE TITLE
Monorepo support

### ISSUE THREAD

**Issue by lewispeel** [rdkcentral/Lightning-CLI#106]
We have a monorepo that uses Yarn workspaces and Lerna.
- The `core` package is a Lightning application which depends on the `account` package.
- Both `core` and `account` depend on `@lightningjs/sdk`.

![image](https://user-images.githubusercontent.com/1321492/105838520-1710b180-5fc8-11eb-99ab-31302ebccaa2.png)

When I try to run `lng build` inside `core` it throws an error because it can't find `@lightningjs/sdk`. This is because part of the build steps in Lightning CLI assumes `node_modules` will be in the same directory as the application. While most of the time this will be true for standalone apps, monorepo dependencies from all the packages are hoisted into a `node_modules` directory in the root of the project to prevent duplicates.

A work around for this is to flag the `core` package with `no-hoist` to prevent its dependencies from being hoisted into the root. This allows `lng build` to be successful but then introduces a different issue where multiple versions of Lightning SDK are being used - one for `core` and another for the packages with hoisting enabled. When using the application in the browser, various error messages appear in the console.

Would it be possible for Lightning to support monorepos?

**Comment by michielvandergeest** [comment]
Thanks for the patience on this topic. We've released v2.8.0 of the CLI last week, that has support for mono-repos.

**Comment by lewispeel** [comment]
Thanks Michiel
