### ISSUE TITLE
LNG_LIVE_RELOAD not starting on correct port

### ISSUE THREAD

**Issue by chiefcll** [rdkcentral/Lightning-CLI#112]
Using env LNG_LIVE_RELOAD starts websocket server on different port than what the build shows (8888 vs 8991)

**Comment by erikhaandrikman** [comment]
Thanks for the report! By default it opens a Websocket connection on port 8888: https://github.com/rdkcentral/Lightning-CLI/blob/09c0b0a434b0f0f7525e48e026eb5842cd942dc7/src/actions/watch.js#L32 but the client listens to 8991 be default: https://github.com/rdkcentral/Lightning-CLI/blob/09c0b0a434b0f0f7525e48e026eb5842cd942dc7/src/helpers/build.js#L56

You can overcome this issue atm by adding `LNG_LIVE_RELOAD_PORT=8888` to your .env (or some other port)
