### ISSUE TITLE
App version after lng dist

### ISSUE THREAD

**Issue by achille1789** [rdkcentral/Lightning-CLI#120]
Hi, I noticed that the app version on the right-bottom corner of the view is not shown (value displayed is undefined), when you run lng dist.
Running lng build, the app version is correctly shown.
SDK version: 4.1.0
CLI version: 2.4.0

**Comment by michielvandergeest** [comment]
This has been fixed https://github.com/rdkcentral/Lightning-CLI/commit/0cebbfbe66de00b7c58d0b9ea62cc19c5b562662
