### ISSUE TITLE
[Feature] Support of browser build using rollup node-resolve plugin

### ISSUE THREAD

**Issue by saikat-mitra** [rdkcentral/Lightning-CLI#128]
While building a lightning app, the rollup config is picking the files of modules mentioned in the "main" field of package.json

There are libraries which may have separate file path for browser and server js. For such npm libraries, the current bundler is always picking the main file path. This causes a server-side file to be injected in the client app of lightning.

**Comment by saikat-mitra** [comment]
This seems to be an issue with rollup build and not with esbuild. 

If we are deprecating rollup then we can close this issue.

**Comment by sarangk-hotstar** [comment]
The same issue has been introduced in esbuild also with #138 where we have added `mainFields: ['module', 'main', 'browser']` in esbuild.config

**Comment by sandeep-vedam** [comment]
Hey @saikat-mitra ,

This is fixed with the PR #193 and is released with version 2.8.1
