### ISSUE TITLE
lng build command report an error that could not lolad lightnings-core.js with correct file path. 

### ISSUE THREAD

**Issue by Eric-Matrix** [rdkcentral/Lightning-CLI#134]
D:\rdk\AcceleratorUI-master>lng build

√ Removing "D:\rdk\AcceleratorUI-master\build" folder

√ Ensuring "D:\rdk\AcceleratorUI-master\build" folder exists

√ Copying support files to "D:\rdk\AcceleratorUI-master\build"

√ Copying static assets to "D:\rdk\AcceleratorUI-master\build"

√ Copying settings.json to "D:\rdk\AcceleratorUI-master\build"

√ Copying metadata.json to "D:\rdk\AcceleratorUI-master\build"

× Error while creating ES6 bundle (see log)

D:\rdk\AcceleratorUI-master\src\index.js → build\appBundle.js...
[!] Error: Could not load /Users/Administrator/AppData/Roaming/npm/node_modules/
@lightningjs/cli/src/alias/lightningjs-core.js (imported by node_modules\@lightn
ingjs\sdk\src\Lightning\index.js): ENOENT: no such file or directory, open 'D:\U
sers\Administrator\AppData\Roaming\npm\node_modules\@lightningjs\cli\src\alias\l
ightningjs-core.js'
Error: Could not load /Users/Administrator/AppData/Roaming/npm/node_modules/@lig
htningjs/cli/src/alias/lightningjs-core.js (imported by node_modules\@lightningj
s\sdk\src\Lightning\index.js): ENOENT: no such file or directory, open 'D:\Users
\Administrator\AppData\Roaming\npm\node_modules\@lightningjs\cli\src\alias\light
ningjs-core.js'

(node:9820) UnhandledPromiseRejectionWarning: Error: Error: Command failed with
exit code 1: C:\Users\Administrator\AppData\Roaming\npm\node_modules\@lightningj
s\cli\node_modules\.bin\rollup -c C:\Users\Administrator\AppData\Roaming\npm\nod
e_modules\@lightningjs\cli\src\configs\rollup.es6.config.js --input D:\rdk\Accel
eratorUI-master\src\index.js --file D:\rdk\AcceleratorUI-master\build\appBundle.
js --name APP_accelerator_ui

D:\rdk\AcceleratorUI-master\src\index.js → build\appBundle.js...
[!] Error: Could not load /Users/Administrator/AppData/Roaming/npm/node_modules/
@lightningjs/cli/src/alias/lightningjs-core.js (imported by node_modules\@lightn
ingjs\sdk\src\Lightning\index.js): ENOENT: no such file or directory, open 'D:\U
sers\Administrator\AppData\Roaming\npm\node_modules\@lightningjs\cli\src\alias\l
ightningjs-core.js'
Error: Could not load /Users/Administrator/AppData/Roaming/npm/node_modules/@lig
htningjs/cli/src/alias/lightningjs-core.js (imported by node_modules\@lightningj
s\sdk\src\Lightning\index.js): ENOENT: no such file or directory, open 'D:\Users
\Administrator\AppData\Roaming\npm\node_modules\@lightningjs\cli\src\alias\light
ningjs-core.js'

    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\@lightningjs\cli\
src\helpers\build.js:196:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9820) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). To termina
te the node process on unhandled promise rejection, use the CLI flag `--unhandle
d-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejectio
ns_mode). (rejection id: 3)
(node:9820) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

**Comment by michielvandergeest** [comment]
This is a known issue on Windows machines when the root of the Lightning project is on a different drive (`D:\` in your case) than where Node / Npm are installed. So far we haven't been able to find a fix for this issue.

The only thing I can recommend is to move the Lightning project to your `C:\` drive.

**Comment by lig** [comment]
Please, use proper source formatting using backticks to avoid random mentions:)

**Comment by Eric-Matrix** [comment]
> This is a known issue on Windows machines when the root of the Lightning project is on a different drive (`D:\` in your case) than where Node / Npm are installed. So far we haven't been able to find a fix for this issue.
> 
> The only thing I can recommend is to move the Lightning project to your `C:\` drive.

Got it, thanks very much.

**Comment by Eric-Matrix** [comment]
> Please, use proper source formatting using backticks to avoid random mentions:)
