### ISSUE TITLE
Cannot import houndify

### ISSUE THREAD

**Issue by CooperCao** [rdkcentral/Lightning-CLI#151]
We are going to use houndify in the lightting app, but cannot use import Houndify from "houndify"; 

https://www.npmjs.com/package/houndify

Uncaught ReferenceError: require$$0$3 is not defined

**Comment by sandeep-vedam** [comment]
Hey @CooperCao ,

Can you post more info about this issue? Are you using browser version or node version of the houndify?
This helps us in debugging the issue in a better manner.
