### ISSUE TITLE
Invalid bundle when app creates Axios Instances.

### ISSUE THREAD

**Issue by pallard-src** [rdkcentral/Lightning-CLI#156]
Hi,

When we tried to migrate to the new CLI version 2.7.0 and we noticed that the generated bundle was not valide and the following error was displayed in the console:

<img width="566" alt="Capture d’écran, le 2021-11-25 à 15 13 28" src="https://user-images.githubusercontent.com/87981092/143496316-ef920bf3-51da-4c96-bfeb-e0d05da530aa.png">

After investigation, [it appears that this issue is caused by Rollup](https://github.com/axios/axios/issues/4153). Sadly tho, the proposed workaround is only available to `yarn` because the `resolutions` configuration is not yet available for `npm` ([currently under development](https://github.com/npm/statusboard/issues/343) as `overrides`).

Would it be possible to update the rollup dependencies within the CLI ?

I took the liberty to [create a clean project to demo the issue](https://github.com/pallard-src/lightning-cli-axios) that you can fork.

Thank you !

**Comment by michielvandergeest** [comment]
Thanks for this wonderfully detailed bug report! Especially adding an example project for reproducing the error 😊

I'll make sure that we'll do some additional investigation on our end as well and try to get a solution out asap.

**Comment by michielvandergeest** [comment]
Hi @pallard-src, we've checked the issue and Sandeep has created a PR updating a rollup plugin. This seems to resolve the issue in the example project. Would you mind taking a look at PR #157 and see if it solves your issue in general as well? Thanks!

**Comment by pallard-src** [comment]
@michielvandergeest The fix does seem to work :)

Thank you for the prompt response and fix.

**Comment by doesdev** [comment]
PSA: If you're like me and think you're up to date on your rollup plugins, it's possible that you're still using an outdated source. Specifically (in this case), `rollup-plugin-commonjs` has been replaced by `@rollup/plugin-commonjs`. There are others which follow the same pattern, but this is the one causing this particular problem.
