### ISSUE TITLE
[Feature] Make default value for App identifier match App name

### ISSUE THREAD

**Issue by robbertvancaem** [rdkcentral/Lightning-CLI#160]
When creating a new Lightning App, the user is asked to input the name of their Lightning App. Directly after that, the App identifier is asked. This defaults to `com.metrological.app.myawesomeapp`, matching the default app name of `My Awesome App`. 

It would be nice to automatically use the app name in the default App identifier. For example, when I'm creating an app with the name of 'My First Lightning App', the proposed App identifier could be `com.metrological.app.myfirstlightningapp`. 

I think it should be possible by passing the `config` (or only `config.appName`) to the `askAppId` function, at: 
https://github.com/rdkcentral/Lightning-CLI/blob/74a26b7a7756c5dba51121f66cfdf1ea2907789c/src/actions/create.js#L79

Then, the name should be lowercased and trimmed of spaces and used as a default in: 
https://github.com/rdkcentral/Lightning-CLI/blob/74a26b7a7756c5dba51121f66cfdf1ea2907789c/src/actions/create.js#L43

**Comment by michielvandergeest** [comment]
Added in #160, #162 and #172.

This feature will be included in the next L-CLI release.
