### ISSUE TITLE
Live reload

### ISSUE THREAD

**Issue by elsassph** [rdkcentral/Lightning-CLI#165]
Can't seem to make the feature work...

I've created a `.env` file (as in your demo app) - this would be a good information to put in the doc BTW, with:
```
LNG_BUNDLER=esbuild
LNG_LIVE_RELOAD=true
LNG_LIVE_RELOAD_PORT=8888
LNG_BUILD_SOURCEMAP=inline
LNG_BUILD_MINIFY=false
```
(I tried with or without the port variable)

Then running `lng watch` to have continuous building (I can see it's using `esbuild` indeed).

Then running `lng serve` in another terminal.

When I make code changes I can see the code being rebuilt, but app doesn't reload in the browser (Chrome or FF).

**Comment by sandeep-vedam** [comment]
Hey @elsassph,

You can use 'lng dev' command to make work with your use case above.

Thanks,
Sandeep

**Comment by elsassph** [comment]
Awesome - I should have tried that.

`LNG_BUNDLER` and `LNG_LIVE_RELOAD` are missing in the doc BTW: https://rdkcentral.github.io/Lightning-CLI/#/environmentvariables

**Comment by sandeep-vedam** [comment]
Hey @elsassph ,

We will update the documentation in our upcoming release.

Thanks,
Sandeep
