### ISSUE TITLE
Broken dep 'colors'

### ISSUE THREAD

**Issue by cidevant** [rdkcentral/Lightning-CLI#167]
Author of 'colors' npm package intentionally broke a package, so everything is broken now. https://github.com/Marak/colors.js/commit/074a0f8ed0c31c35d13d28632bd8a049ff136fb6

 `http-server` uses `colors` package, so after fresh install `npm install -g rdkcentral/Lightning-CLI` there is no possibility to run `lng dev`

`colors` version 1.4.0 works

**Comment by michielvandergeest** [comment]
The `http-server` package has been upgraded in the last few hours (they've decided to move away from `colors.js` to `chalk`).

We've updated the `http-server` dependency of the Lightning CLI and are doing a full regression test now to make sure the major version bump doesn't introduce any other issues, before pushing out this hotfix.
