### ISSUE TITLE
[Bug] lng dev, lng dist/serve commands failing 

### ISSUE THREAD

**Issue by jbstocker** [rdkcentral/Lightning-CLI#170]
When running lng dev or lng dist+serve commands the lng cli is failing - likely due to downstream dependency on colors.js. Output:
![image](https://user-images.githubusercontent.com/22012643/150987163-488e98cc-6236-4660-9c42-40429381af68.png)

I believe this is due to dependency on http-server which recently made an update to alleviate the issue with colors.js: 
https://www.npmjs.com/package/http-server/v/14.1.0
https://github.com/http-party/http-server/releases/tag/v14.1.0

This is a breaking issue

**Comment by michielvandergeest** [comment]
Thanks for bringing this up :)

There is a fix in place already, we just have to wrap up our regression testing of the major version bump of http-server package.

Will update here once it's merged to master an published to NPM.

**Comment by michielvandergeest** [comment]
Lightning-CLI 2.72. has been merged to master and released on NPM.
