### ISSUE TITLE
Running `lng upload` doesn't automatically install dependencies

### ISSUE THREAD

**Issue by robbertvancaem** [rdkcentral/Lightning-CLI#175]
Hey guys, 

Great work on this CLI, it's really convenient. Today I ran into a pretty specific use case, I thought I'd share it with you to see if this is something that could be improved. 

I'm working on a Lightning application, and in the `dev` branch I have installed some dependencies and removed others compared to the `main` branch. Now, a tiny bugfix needed to be made on the `main` branch. So I committed the code and ran `lng upload`. 

Unfortunately, the application uploaded threw some errors related to packages being missing (since I deleted them locally and added some new dependencies as well). Therefor I needed to version bump the application and manually run `npm install` before running another `lng upload`. 

Ideally, `lng upload` or `lng build` would remove the `node_modules` and install them according to the `package-lock.json` file. I can imagine that there is a slight performance loss here, but perhaps it prevents some faulty deployments. 

Looking forward to hear if you think this is a good idea :-) 😎

**Comment by michielvandergeest** [comment]
hey @robbertvancaem, I think your idea makes sense, to do a fresh install of the node_modules upon upload. 

I'm closing this one since you can now implement this feature yourselves in the Metro-CLI :)
