### ISSUE TITLE
Support for ECMAScript 2020 features

### ISSUE THREAD

**Issue by mauro1855** [rdkcentral/Lightning-CLI#181]
Hi Lightning-CLI team,

When creating a project using the CLI (with ```lng create```) it seems the new project doesn't support ECMAScript 2020 features out of the box. For example, if I want to use the new very useful Optional Chaining feature, I find that:
1. ESLint throws an error, saying the syntax is unexpected.
2. The transpilation to ES6 (when doing ```lng dist``` or ```lng upload```) does not properly transpile the syntax - the side effect is that the app won't work in some STBs.

I have a manual procedure to fix this:
1. Change the ```ecmaVersion``` property in the ```.eslintr.js``` file to remove ESLint errors
2. Manually install the correct babel plugins and add them to the ```babel.config.js``` file. For example, for optional chaining I need to ```npm install --save-dev @babel/plugin-proposal-optional-chaining```.

I would need to repeat step 2 for each ECMAScript 2020 feature I want to use, and only then my code is transpiled correctly to ES6

Would you be able to update the CLI to support out-of-the-box ECMAScript 2020 and transpile it without us having to change our projects?

**Steps to reproduce:**
1. Create a new project with ```lng create``` and ESLint
2. Add the following code to your App.js: 
```
_init() {
    const anObject = {
      foo: 'bar',
      fun: () => true,
    }

    console.log('Optional chaining works with undefined object? ', !anObject.something?.hello)
    console.log('Optional chaining works with object? ', !!anObject?.foo)
    console.log('Optional chaining works with function? ', !!anObject?.fun?.())
    console.log('Optional chaining works with non existing function? ', !anObject?.fun2?.())
    console.log('Nullish coalescing works? ', anObject?.fun2?.() ?? true)
}
```
3. Create a distribution with ```lng dist```.
4. Check your distribution code in ```/dist/es6/js/appBundle.js``` to see if the syntax was transpiled.

**Desired behaviour:**
Syntax should be transpiled and ESLint shouldn't throw any errors.

**Comment by sandeep-vedam** [comment]
Hey @mauro1855 

Thanks for your observations. 
Babel preset(already available in CLI) does this as it supports most of the ECMA 2020 features. Please have a look at the transpilation functionality with the sample project available at https://github.com/sandeep-vedam/es2020babeltest
