### ISSUE TITLE
Build error from esbuild when there is a dependency on crypto-js

### ISSUE THREAD

**Issue by Serhii-the-Dev** [rdkcentral/Lightning-CLI#187]
Steps to reproduce:
1. `yarn add crypto-js@4.1.1` or `npm i crypto-js@4.1.1`
2. `LNG_BUNDLER=esbuild lng dev`
3. Observer the error:
```sh
✖ Error while creating ES5 bundle using [esbuild] (see log)
 
--------------------------------------------------------------
Build failed with 1 error:
node_modules/crypto-js/core.js:50:25: error: [plugin: babel] ENOENT: no such file or directory, open 'crypto'
--------------------------------------------------------------
```
The same will happen with any other packages depending on polyfills of the Node built-ins.

**Comment by michielvandergeest** [comment]
Hi @Serhii-the-Dev thanks for this report.

I'd like to ask for a few additional details:
- does this issue only happen when using esbuild as a bundler or also rollup?
- does it only happen with es5 output, or also es6?
- does it only happen with this crypto-js version? Would you mind checking it with crypto-js v3

**Comment by Serhii-the-Dev** [comment]
Hi @michielvandergeest 
1. Yes, the issue could be reproduced with `esbuild` bundler only
2. Both `es5` and `es6` build modes are affected
3. It happens with `crypto-js` 4+ only, previous versions are not relying on polyfills
