### ISSUE TITLE
LNG_LIVE_RELOAD missing in documentation

### ISSUE THREAD

**Issue by robbertvancaem** [rdkcentral/Lightning-CLI#196]
Hi team,

I thought I've seen the `LNG_LIVE_RELOAD` environment variable in the past. I was surprised to see it referenced [in the docs](https://github.com/rdkcentral/Lightning-CLI/commit/a3942e0ef97114000bba696275e2c0378694f379#diff-6bd562ee4209b546ef734d9753170d21e17a26be9515897b245709b53fa8bf8eR65-R69) (in a merged feature branch) on Github, but not here: 
https://lightningjs.io/docs/#/lightning-cli-reference/EnvironmentVariables?id=environment-variables

It seems like this property was accidentally removed from the docs during this merge action:
https://github.com/rdkcentral/Lightning-CLI/commit/8a7eb49a994f7bf16c378202ee093fcf0610c7b4#diff-6bd562ee4209b546ef734d9753170d21e17a26be9515897b245709b53fa8bf8e 

Can you please add it to the docs again?

**Comment by sandeep-vedam** [comment]
This issue is fixed in #197 and is released in the version 2.8.1
