### ISSUE TITLE
Husky's pre-commit hook is not working after `lng create`

### ISSUE THREAD

**Issue by robbertvancaem** [rdkcentral/Lightning-CLI#198]
Hi there, 

**Edit/Update**
Surprisingly, after using a different version of Node - `v17.3.1` instead of `v12.22.9` - the `pre-commit` hooks works perfectly, as expected. Is there a recommended version of Node? I don't see a reference to that in the documentation.

---------------

After just creating a new project using `lng create`, adding a `'no-console': 'error'` rule in `.eslintrc.js` and adding a `console.log` in one of my project files, I would expect the Husky pre-commit hook to kick in and prevent me from commiting this. However, the change got committed anyway. 

I believe this is because the current implementation of Husky's `pre-commit` script in the `package.json` as generated by `lng create` is not following Husky's latest guidelines.

```json
{
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
}
```

They have moved their commands from the `package.json` into a dedicated `.husky` folder, where a `pre-commit` script would have a dedicated `pre-commit` file, including a configuration like for example: 

```sh
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged
```

They have documented the reasons for this change here: https://blog.typicode.com/husky-git-hooks-javascript-config/

I 'solved' this by running an `npx husky-init`, which basically creates the `.husky` folder and `pre-commit` file for me. I also removed the `husky` part from the `package.json`.

I think there are a couple of fixes to this:
1. Remove husky from `devDependencies` and from `package.json`
2. Add `.husky` folder containing `pre-commit` file containing contents as mentioned above into `fixtures`. I'm not sure if this also requires a `husky install` in the `prepare` script of the `package.json`, as mentioned [here](https://typicode.github.io/husky/#/?id=install).

**Comment by sandeep-vedam** [comment]
Hi @robbertvancaem 

This issue is fixed and release in Lightning CLI Version 2.9.0
