### ISSUE TITLE
CLI CI/CD Compatibility ( lng upload )

### ISSUE THREAD

**Issue by maxiolin** [rdkcentral/Lightning-CLI#206]
Hi guys, I'm working on a Jenkins job to upload my app to the metrological dashboard using the lightning CLI.

My issue is that the upload command doesn't take parameters and always asks me to insert the API KEY after the command was initiated, in an interactive way I mean.

Do you know if there's a workaround for this, something that allows me to pass the API KEY to the command as I'm executing it?

As you may know, CI/CD pipelines don't allow you to interact with the commands.

**Comment by michielvandergeest** [comment]
Hi @maxiolin, your observation is correct. Currently the Lightning-CLI doesn’t work well with upload via CI/CD pipelines. It’s simply a scenario that wasn’t considered as an expected use case when the upload functionality was implemented.

As you may know the functionality to upload to the Metrological Platform is currently *deprecated* in the Lightning-CLI and will be removed entirely in our upcoming January release. It’s being replaced by the Metro-CLI (https://github.com/metrological/metrological-cli), so I suggest to open a ticket in that repository.

In fact there is a branch (feature/store/backendtoken) over at the Metro-CLI that might be interesting for you, where the API token is stored on the file system. Another option would be to pass the API key as an option.

But again, it’s best to pick this up with the Metrological team that is maintaining the upload functionality.
