### ISSUE TITLE
App bundle created with esbuild is not exposing a constructor

### ISSUE THREAD

**Issue by Serhii-the-Dev** [rdkcentral/Lightning-CLI#208]
When uploading an app into the Metrological store, it expects that `window['APP_' + appId]` will be a constructor, which is true in case of a build created with Rollup, however esbuild exposing an object containing a `default` field, which, in turn is a pointer to a constructor. Therefore, an app created with esbuild will not start in the Metrological app store.

**Comment by michielvandergeest** [comment]
Hi @Serhii-the-Dev, yes we are aware of this. But unfortunately it's not something that we as the Lightning Open Source team can fix. To our knowledge it's not possible for ESbuild to produce a constructor, similar to how Rollup does it (and how the Metrological store expects it's packages).

You best pick this up with the Metrological platform team and see if they can add a compatibility for Apps built with ESbuild.
