### ISSUE TITLE
.gitignore getting written every time we run a build

### ISSUE THREAD

**Issue by ricardo-a-alves-alb** [rdkcentral/Lightning-CLI#209]
Hi,

Each time we run a build, the .gitignore file is checked to see if it has every entry necessary.

However, since it is using `os.EOL` to split each line and we are using mixed OS (Win/Mac) and our file is in LF mode, for some it works as expected and for others it keeps getting written.

Any better solution or any approach we should take to mitigate this problem?

https://github.com/rdkcentral/Lightning-CLI/blob/727ffafb568763b710f68d2fe66760bff95cc699/src/helpers/build.js#L255-L277

**Comment by michielvandergeest** [comment]
Hi @ricardo-a-alves-alb, I understand that must be annoying!

The difficulty is indeed the differences is EOL per platform. Let me see if we can figure something out to for this :)

**Comment by michielvandergeest** [comment]
hi @ricardo-a-alves-alb we have a fix for this issue (https://github.com/rdkcentral/Lightning-CLI/pull/212). We've tested on Windows, Mac OSx and Linux (Ubuntu) platforms and haven't encountered any problems.

Would you mind checking if this fix solves the issue for your team as well? Then we'll make sure to include this in the upcoming release (which will be January '23)
