### ISSUE TITLE
Allow using a different .env than the one on the root folder

### ISSUE THREAD

**Issue by ricardo-a-alves-alb** [rdkcentral/Lightning-CLI#214]
Hello,

For each platform we support, we need to use different tokens. For that, we were thinking about using a environment variable to achieve that, however, since you are reading the environment variables using `dotenv` library with the default config, it only reads the `APP_` keys from the `.env` file on the root folder and ignores the variables we set on `process.env`.

https://github.com/rdkcentral/Lightning-CLI/blob/98c9231e2d68fa3ad22c15124a5709dadc9a009b/src/configs/rollup.es5.config.js#L54-L59

How should we approach this scenario?
1) Change this so we can provide a different path for `.env`
2) Read `APP_` variables from `process.env` also. This would cause an issue because which one would take prevalence, `process.env` or `.env` variables?

**Comment by frank-weindel** [comment]
I think it'd be reasonable to read the `APP_` vars from `process.env` and have them take precedent over the ones specified in the `.env` file. @michielvandergeest what are your thoughts?

**Comment by ricardo-a-alves-alb** [comment]
> I think it'd be reasonable to read the `APP_` vars from `process.env` and have them take precedent over the ones specified in the `.env` file. @michielvandergeest what are your thoughts?

Yes, that approach suits us.

**Comment by michielvandergeest** [comment]
Yeah agreed. Let's also include any other vars set on the process.env. And I think it's fair for APP vars to take precedence in case of naming collisions.

We're working on getting this functionality in.
