### ISSUE TITLE
LNG DIST ignores esEnv parameter in settings.json

### ISSUE THREAD

**Issue by nstansbury** [rdkcentral/Lightning-CLI#224]
Given a custom `settings.[ENV].json`

`settings.es5.json`:
```
{
  "appSettings": {
    "stage": {
      "clearColor": "0x00000000",
      "useImageWorker": false,
      "canvas2d": false,
      "forceTxCanvasSource": true
    },
    "debug": false,
  },
  "platformSettings": {
    "path": "./static",
    "esEnv": "es5",
    "log": false,
    "showVersion": false,
    "inspector": false,
    "lazyDestroy": false,
    "destroyOnHistoryBack": true
  }
}
```
The following options in `package.json`:
```
   ...
    "build:es5": "NODE_ENV=development LNG_BUILD_FOLDER=build/es5 LNG_SETTINGS_ENV=es5 lng build",
    "dist:es5": "NODE_ENV=production LNG_DIST_FOLDER=dist/es5 LNG_SETTINGS_ENV=es5 lng dist"
```

`npm run build:es5`  builds an ES5 bundle
`npm run dist:es5`  builds an **ES6** bundle using the same json config

**Comment by nstansbury** [comment]
As this is flagged as "enhancement" Is this the expected behaviour that `lng dist` ignores parameters in `platformSettings`?

**Comment by sandeep-vedam** [comment]
Hello @nstansbury 

I appreciate you bringing this to our attention. Unfortunately, we haven't integrated support for this particular feature on our LNG dist just yet.

However, in the meantime, you can still create a dist version with es5 by using the command:

lng dist --es5

Rest assured that we are taking note of your request and we will definitely consider adding support for it in future releases. Thank you for your understanding and patience!
