### ISSUE TITLE
Sourcemaps in production?

### ISSUE THREAD

**Issue by cidevant** [rdkcentral/Lightning-CLI#242]
## 1) Question
Why sourcemaps are force disabled in `lng dist`? Any valid reason for it? I think it should be configurable.

ES6: https://github.com/rdkcentral/Lightning-CLI/blob/9ea454cf94b7d26b304cf92141691245e8f48ab6/src/actions/dist.js#L56
ES5: https://github.com/rdkcentral/Lightning-CLI/blob/9ea454cf94b7d26b304cf92141691245e8f48ab6/src/actions/dist.js#L59

## 2) Confusion with `options` param passed to build helpers:

2.1) Parent function sends `options` param
**https://github.com/rdkcentral/Lightning-CLI/blob/9ea454cf94b7d26b304cf92141691245e8f48ab6/src/helpers/build.js#L172**

2.2) rollup **REFLECTS** options param passed from parent (overrides rollup config)
https://github.com/rdkcentral/Lightning-CLI/blob/9ea454cf94b7d26b304cf92141691245e8f48ab6/src/helpers/build.js#L223

2.3) esBuild **IGNORES** options param
https://github.com/rdkcentral/Lightning-CLI/blob/9ea454cf94b7d26b304cf92141691245e8f48ab6/src/helpers/build.js#L184

## 3) Some logic for sourcemaps is present in bundlers configs which makes everything inconsistent

https://github.com/rdkcentral/Lightning-CLI/blob/9ea454cf94b7d26b304cf92141691245e8f48ab6/src/configs/esbuild.es5.config.js#L33

https://github.com/rdkcentral/Lightning-CLI/blob/9ea454cf94b7d26b304cf92141691245e8f48ab6/src/configs/esbuild.es6.config.js#L31

https://github.com/rdkcentral/Lightning-CLI/blob/9ea454cf94b7d26b304cf92141691245e8f48ab6/src/configs/rollup.es5.config.js#L119

https://github.com/rdkcentral/Lightning-CLI/blob/9ea454cf94b7d26b304cf92141691245e8f48ab6/src/configs/rollup.es6.config.js#L109

**Comment by cidevant** [comment]
Should I create MR for it ?

**Comment by sandeep-vedam** [comment]
Hey @cidevant 

Thanks for raising these inconsistencies to our attention. We agree that there is no valid justification. We'll pick this up and It probably won't make the upcoming July release, but we'll make sure to add this in the next release.
