### ISSUE TITLE
Default value for LNG_BROWSER_BUILD

### ISSUE THREAD

**Issue by scailbc** [rdkcentral/Lightning-CLI#247]
Hello everybody, I'm wondering why the env variable `LNG_BROWSER_BUILD` is set to false as default value.

From what I saw it was added in [v2.8.1](https://github.com/rdkcentral/Lightning-CLI/tree/v2.8.1) as a solution related to [issue #128](https://github.com/rdkcentral/Lightning-CLI/issues/128) and [PR130](https://github.com/rdkcentral/Lightning-CLI/pull/130), [PR138](https://github.com/rdkcentral/Lightning-CLI/pull/138) and [PR193](https://github.com/rdkcentral/Lightning-CLI/pull/193). In short the problem was that some imported libraries would break, because they load the version intended for Node instead of the version intended for the browser.

In practice the LNG_BROWSER_BUILD is used while building with Esbuild or Rollup and changes the parameter [main-fields](https://esbuild.github.io/api/#main-fields):

- if false (default value): it's `module, main, browser`
- if true: it's `module, browser, main`

Why it is false by default? Is it because it was the configuration used before [v2.8.1](https://github.com/rdkcentral/Lightning-CLI/tree/v2.8.1) or there is another reason?
Esbuild by default [gives priority to `browser`](https://esbuild.github.io/api/#platform) over `main`, so it seems like setting the value to true makes more sense.
Let me know. Thanks

**Comment by sandeep-vedam** [comment]
Hi @scailbc,

We intentionally made this change to align with the older configuration before [v2.8.1](https://github.com/rdkcentral/Lightning-CLI/tree/v2.8.1). LNG_BROWSER_BUILD is set to false by default.
Thanks
