### ISSUE TITLE
Problem with newest CLI version. See attachment

### ISSUE THREAD

**Issue by damir-delijic** [rdkcentral/Lightning-CLI#257]
![Error](https://github.com/rdkcentral/Lightning-CLI/assets/57603801/877b868f-ecc2-4f56-94f5-05e3c0bfec24)

I resolved the error by setting LNG_CUSTOM_ESBUILD=false in .env file and by adding custom es6 and es5 configurations in my root folder with this inside of both of them: 
{
    entryPoints: [`${process.cwd()}/src/index.js`]
}

**Comment by damir-delijic** [comment]
![image](https://github.com/rdkcentral/Lightning-CLI/assets/57603801/7ccbd178-000c-44cc-b559-ff549bdb31e6)
![image](https://github.com/rdkcentral/Lightning-CLI/assets/57603801/2b4b9b0b-0806-4222-87d2-778ce8053d83)

Basically, if there is no custom configuration, it is trying to use the in operator on an undefined variable which throws an error.

**Comment by uguraslan** [comment]
Hey @damir-delijic, thank you for bringing this issue to our attention. As you already identified, the source of the problem is using `in` operator on `customConfig` without checking if `customConfig` is not `undefined`. We will be fixing this as soon as possible.

**Comment by ricardo-a-alves-alb** [comment]
@uguraslan Rollup also has the same issue.
