### ISSUE TITLE
Is possible to evaluate to pass the port as a parameter of `lng serve`?

### ISSUE THREAD

**Issue by mattiapontonio** [rdkcentral/Lightning-CLI#41]
@michielvandergeest thanks. Is possible to evaluate to pass the port as a parameter of `lng serve`?

_Originally posted by @mattiapontonio in https://github.com/WebPlatformForEmbedded/Lightning-CLI/issues/39#issuecomment-608328256_

**Comment by michielvandergeest** [comment]
Possible with Lightning-CLI v1.7.0: https://github.com/rdkcentral/Lightning-CLI#bahavior-environment-variables
