### ISSUE TITLE
lng upload - how it works

### ISSUE THREAD

**Issue by mattiapontonio** [rdkcentral/Lightning-CLI#57]
Hello,

I've registered here: https://dashboard.metrological.com/
If i generate the API key and upload the app, what I'm expecting to see?
There is some staging environment?
How about my express server?

Best regards
Mattia

**Comment by michielvandergeest** [comment]
Only your Lightning App will be uploaded to the Metrological Back office. Once uploaded your App will go into QA, and once approved Operators will be able to publish your app in their Store.

Your express server should not be part of the upload and should be hosted somewhere else (by yourself).
