### ISSUE TITLE
Managing Environment Variables

### ISSUE THREAD

**Issue by AndriyShpyra** [rdkcentral/Lightning-CLI#58]
Hello!

I'm looking for a way to declare different API URLs for local development build and production build.
Is it possible to set the environment variables in package.json or via CLI?

**Comment by mattiapontonio** [comment]
https://github.com/rdkcentral/Lightning-CLI/issues/50

**Comment by AndriyShpyra** [comment]
@mattiapontonio, thank you for reply.

In my case, I have two different API endpoints (test, prod)
For instance, when I'm running 'lng dev' command, the dist folder is being created, and local server launches.
But It would be nice to pass a local variable that indicates whether to use prod URL or DEV URL
instead of each time manually change URL value before building dist folder

**Comment by mattiapontonio** [comment]
I agree. But as mention in the comment lng dev is just a "bonus". You can simply build and serve the folder via Your own Node server with your configs.

**Comment by michielvandergeest** [comment]
There are some plans to implement environment variables, that could come in handy for these type of cases. It's currently in local development. No ETA yet.

**Comment by mattiapontonio** [comment]
A quick and easy solution could be spread `[options]` from CLI process using argv to the `http-server` directly.

**Comment by michielvandergeest** [comment]
Support for environment variables are added in Lightning-CLI v1.7.0
https://github.com/rdkcentral/Lightning-CLI#environment-variables
