### ISSUE TITLE
String does not match the pattern of "^(?:@[a-z0-9-*~][a-z0-9-*._~]*/)?[a-z0-9-~][a-z0-9-._~]*$".

### ISSUE THREAD

**Issue by mattiapontonio** [rdkcentral/Lightning-CLI#62]
![image](https://user-images.githubusercontent.com/44380480/84121178-14f8e300-aa37-11ea-817f-c3cdd3d58eb8.png)

I get this warning. I get the same warning also when the app uses the name like `com.app.name`. Seems that the pattern should be like `com-app-name`.

**Comment by mattiapontonio** [comment]
@michielvandergeest 2 thing:

You can read and parse the JSON or i do not know if there is some npm API. Code  template in code Is not a good practise. Anyway the second issue remains:
The suggested naming of the package is invalid stands for VS Code...
Kind regards
Mattia

**Comment by RishiSetpal7** [comment]
> This warning is because `{$appId}` is obviously not a valid NPM package name.
> 
> However this is not the project's real package.json. Merely the fixture used as a blueprint when generating a new project. And the {$appId} string will be replaced when generating the new project.

according to then $appName should also show error !?
