### ISSUE TITLE
Auto update version inside metadata.json

### ISSUE THREAD

**Issue by MykhailoDz** [rdkcentral/Lightning-CLI#64]
It will be nice to have a feature to auto-update version inside metadata.json

**Comment by michielvandergeest** [comment]
@MykhailoDz can you explain a bit further how you would see this feature? What event(s) should trigger such an automatic version update in metadata.json, for example?

**Comment by MykhailoDz** [comment]
@michielvandergeest for example "lng build", "lng update-version" or "lng upload"
