### ISSUE TITLE
App Background Transparency

### ISSUE THREAD

**Issue by nunofaria** [rdkcentral/Lightning-CLI#71]
- **clearColor** with alpha value to 0 (transparent) in **settings.json** is rendered obsolete due to the **background: black;** property being set at:
  - fixtures/dist/index.es5.html
  - fixtures/dist/index.es6.html

proposed fix in the following pull request #72

**Comment by michielvandergeest** [comment]
Thanks! Merged into `dev`-branch, will be published to master in a next release.
