### ISSUE TITLE
NPM Inconsistencies

### ISSUE THREAD

**Issue by akashkpuri** [rdkcentral/Lightning-CLI#81]
When creating a new Lightning app using [PNPM](https://pnpm.js.org/en/) as our node cli and the [strictPeerDependencies](https://pnpm.js.org/en/3.0.0/pnpm-install#strict-peer-dependencies) option enabled, I get the following error trying to install the lightning cli:  

`wpe-lightning-cli: rollup-plugin-terser@6.1.0 requires a peer of rollup@^2.0.0 but version 1.32.1 was installed`

Any chance we could update the rollup version used in the CLI (and Lightning) packages to use rollup 2.0.0 and avoid this invalid versioning?

**Comment by octogonz** [comment]
Alternatively, Lightning could downgrade `rollup-plugin-terser` to version 5.3.0 which does not require Rollup 2.

**Comment by michielvandergeest** [comment]
This should be resolved in the v2.0.1 release
