### ISSUE TITLE
Is there any lng command available to kill all running http-server

### ISSUE THREAD

**Issue by naseemshekh20** [rdkcentral/Lightning-CLI#84]
Whenever i am running lng serve it uses/creates new port every time 

**Ex:**
first time >  http://localhost:8080
second time >  http://localhost:8081
third time >  http://localhost:8082

Same this is happening with lng dev, it uses/creates new port every time after file save file changes

There should be a command available to kill all the running http-server

**Comment by michielvandergeest** [comment]
Cmd+c or ctrl+c on the `lng dev` or `lng serve` command should kill the running server.

If a server is still running, `lng serve` should indeed open on the next available port.

Can you provide more info on your environment?

**Comment by naseemshekh20** [comment]
> Cmd+c or ctrl+c on the `lng dev` or `lng serve` command should kill the running server.
> 
> If a server is still running, `lng serve` should indeed open on the next available port.
> 
> Can you provide more info on your environment?

I am using windows and visual studio code, in old lightning SDK ctrl+c was working fine

**Comment by naseemshekh20** [comment]
$ lng serve
Starting up http-server, serving ./build
Available on:
  http://172.20.10.3:8090
  http://192.168.56.1:8090
  http://127.0.0.1:8090
Hit CTRL-C to stop the server
open: http://127.0.0.1:8090

----

$ lng serve
Starting up http-server, serving ./build
Available on:
  http://172.20.10.3:8091
  http://192.168.56.1:8091
  http://127.0.0.1:8091
Hit CTRL-C to stop the server
open: http://127.0.0.1:8091


-----

$ lng serve
Starting up http-server, serving ./build
Available on:
  http://172.20.10.3:8092
  http://192.168.56.1:8092
  http://127.0.0.1:8092
Hit CTRL-C to stop the server
open: http://127.0.0.1:8092

**Comment by naseemshekh20** [comment]
Starting up http-server, serving ./build
Available on:
http://127.0.0.1:8098/

it is keep increasing....

Only restart the PC is the only solution

**Comment by naseemshekh20** [comment]
https://rdkcentral.github.io/Lightning-CLI/#/environmentvariables

LNG_SERVE_PORT=3333 lng serve
