### ISSUE TITLE
lng build hangs when importing a JS file from outside the app root

### ISSUE THREAD

**Issue by frank-weindel** [rdkcentral/Lightning-CLI#88]
I'm working on an app that involves an HTML app running on a mobile or desktop device and a Lightning app running on a TV. I'd like the two apps to share the same common app dependencies via an import

Directory structure
```
/common
- /SocketClient.js
/tv-app
- /src
  - /App.js
/mobile-app
```

I'm trying to import SocketClient.js from the Lightning app's App.js like so:
```
import SocketClient from '../../common/SocketClient.js'
```

However when I run `lng build`, rollup seems to hang indefinitely with no error or warning.

<img width="405" alt="Screen Shot 2020-10-19 at 3 42 29 PM" src="https://user-images.githubusercontent.com/6070611/96503801-cb5ca800-1221-11eb-94f1-f7c57683c895.png">

Attached is a sample project to reproduce. Simply extract, go to the "tv-app" directory. Run `npm install`, and then `lng build`

[lightning-common-rollup-hang.zip](https://github.com/rdkcentral/Lightning-CLI/files/5404324/lightning-common-rollup-hang.zip)

If any of you know another pattern you can recommend to achieve the same "commonality" I'd love to hear about it. Thanks!

**Comment by erikhaandrikman** [comment]
Sorry for the delay in answering this question. The CLI now supports [esbuild](http://www.lightningjs.io/announcements/lightning-cli-esbuild) and that bundler is able to resolve the path to file outside of app directory
