### ISSUE TITLE
Code splitting is missing

### ISSUE THREAD

**Issue by Serhii-the-Dev** [rdkcentral/Lightning-CLI#99]
While working with large codebase that includes third-party libraries(state management, video players, analytics systems), code splitting allows to reduce time required to load an app. Utilization of the SDK's routing mechanism may be a very good option to split code on which each route depends + generic vendor bundles. A [Next.js](https://github.com/vercel/next.js/) per-page code splitting is a very good example.

**Comment by Serhii-the-Dev** [comment]
Hi,

Just want to add some clarity to this issue: we tried an alternative approach without the `lng-cli` building an app with Webpack. With proper chunking configuration it's possible to generate a main chunk that will load all other parts in runtime. However, it's unclear if this approach may be considered as supported in the Metrological environment:

1. Chunks are loaded with a base URL that differs from an URL that hosts an app. We could not resolve that URL in build-time since it contains some hash Metrological adds to an app version. Potentially it could be solved by Webpack's [auto-resolution of a public path](https://github.com/webpack/webpack/pull/11258), however it's need to be tested to confirm. It seems like a more suitable approach to have some first-class support by the ML App store for such an approach instead relying on a third-party.
2. All the `script` tags added during app lifecycle will be left intact slowly flooding the app store page.

Therefore, even if we could contribute to this repository, some input from the maintainers is required to ensure a proposed approach will be suitable for the main environment `lng-cli` is designated for.

**Comment by michielvandergeest** [comment]
Hi @Serhii-the-Dev thanks for your patience on this issue

You are completely correct that the inner workings of the Metrological app platform are a limiting factor in adding this type of (awesome) features and functionality to the CLI

I believe the functionality currently is not supported (or allowed) in the context of the Metrological store. So even if we would add it to the Lightning-CLI itself, it would only be useful during development or deployments outside of the Metro store.

We are working by the way on making a more clear separation between the Lightning framework (in the broad sense) and Metrological deployments. 

Back to the feature request itself: while I really like the idea, to be honest I don't think that we will be adding code splitting it in the near future. It's more likely we will include it as a feature of the CLI in the next major Lightning framework release.
